name: 'Push with Fast-Forward Pull, Merge and Rebase Fallback'
description: 'Pushes to a remote repository, and if there is a failure, tries pull with fast-forward first before pull with merge and then rebase'

outputs:
  commitHash:
    description: 'The commit hash of the pushed commit'
    value: ${{ steps.commit.outputs.hash }}

runs:
  using: "composite"
  steps:
    - name: Configure Git
      run: |
        git config --local user.email "$(git show -s --format='%ae' HEAD)";
        git config --local user.name  "$(git show -s --format='%an' HEAD)";
      shell: bash

    - name: Push with Rebase Retry
      run: |
        for i in {1..5}; do
          git push origin $(git branch --show-current) && break || (
            echo "Try pull fast-forward..." && 
            git pull --ff-only origin $(git branch --show-current) || 
            echo "Try pull merge..." && 
            git pull --no-rebase origin $(git branch --show-current) || 
            echo "Try pull rebase..." && 
            git pull --rebase origin $(git branch --show-current)
          ) && 
          git push origin $(git branch --show-current) && break || 
          echo "Retry loop..." && echo ""
          if [ $i -eq 5 ]; then
            echo "Failed to push changes to remote"
            exit 1
          fi
          sleep 5
        done
        echo "hash=$(git rev-parse HEAD | cut -c 1-7)" >> $GITHUB_OUTPUT
      shell: bash

