name: 'Push with Rebase Retry'
description: 'Pushes to a remote repository, and retries rebase if there is a conflict'
runs:
  using: "composite"
  steps:
    - name: Configure Git
      run: |
        git config --local user.email "$(git show -s --format='%ae' HEAD)";
        git config --local user.name  "$(git show -s --format='%an' HEAD)";
      shell: bash
    - name: Push with Rebase Retry
      run: |
        for i in {1..5}; do
          git pull --rebase origin $(git branch --show-current) && git push origin $(git branch --show-current) --force-with-lease && break || echo "Retrying rebase and push..."
          sleep 5
        done
      shell: bash